version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: docker/api.dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - backend
      - frontend
  
  frontend:
    build:
      context: .
      dockerfile: docker/front.dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - backend

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

networks:
  backend:
  frontend:
